### ISSUE TITLE
failed to start the app

### ISSUE THREAD

**Issue by wingkwong** [nandiheath/gatsby-template#1]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

```
 ERROR #98124  WEBPACK

Generating development SSR bundle failed

Can't resolve '../../locales/en/translation.json' in 'C:\foo\gatsby-foo\src\lib'

If you're trying to use a package make sure that '../../locales/en/translation.json' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\lib\i18n.ts:3:0


 ERROR #98124  WEBPACK

Generating development SSR bundle failed

Can't resolve '../../locales/zh/translation.json' in 'C:\foo\gatsby-foo\src\lib'

If you're trying to use a package make sure that '../../locales/zh/translation.json' is installed. If you're trying to use a local file make sure that the path is correct.

File: src\lib\i18n.ts:4:0

not finished Building development bundle - 31.026s
```

* **What is the current behavior?**

translation.json not found

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

running 

```
npm run dev
```

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Suggest to include an empty translation.json in both en and zh directory

**Comment by wingkwong** [comment]
another issue

```
 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the onCreatePage lifecycle:

Cannot read property 'forEach' of undefined

  76 |     deletePage(page);
  77 |
> 78 |     languages.forEach((lang, index) => {
     |               ^
  79 |       const isDefaultLang = index === 0;
  80 |       const path = isDefaultLang ? page.path : `/${lang}${page.path}`;
  81 |       createPage({

File: gatsby-node.js:78:15
```

**Comment by wingkwong** [comment]
second thought. It seems you tend to read those locales from the spreadsheet and write them to translation.json. 

```

 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the sourceNodes lifecycle:

ENOENT: no such file or directory, mkdir 'locales/<!DOCTYPE html><html><head><meta name="google" content="notranslate"><meta name="viewport" content="target-densitydpi=device-dpi'
```

**Comment by nandiheath** [comment]
This is solved with the latest commit 
Thank you for reporting!
